#!/bin/bash

# A script for automated testing 

TMP=/tmp/do_test.out

function try_make
{
case $1 in
dot) make dot.code;;
run) make run;;
vhdl) make vhdl;;
*) make $1.run;;
esac
case $? in
0) echo "OK";;
*) echo "FAILED";;
esac
}

function domake
{
echo -n "  -> making $2 in $1 ... "
(cd $1; make $2.run) > /dev/null 2>&1
case $? in
0) echo -e "\033[32mOK\033[0m";;
*) failed=true; echo -e "\033[31mFAILED\033[0m"; (cd $1; make $2.clobber) > /dev/null 2>&1;;
esac
}

function make_test 
{
    failed=false
    (cd $1; make clean) > $TMP 2>&1
    domake $1 run 
    domake $1 dot
    domake $1 vhdl
    (cd $1; make clean) > $TMP 2>&1
}

if [ $1 = "all" ]
then
    shift
    echo "** Running test in $1... "
    make_test $1 2>&1
    if $failed ; then
        exit 0
    else
        exit 1
    fi
else 
    echo -n "Testing $1 in $2... "
    (cd $2; try_make $1 && make clean) > $TMP 2>&1
    grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
    grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
    grep "OK" $TMP >/dev/null && exit 1
    exit 0
fi
