run: 
	../../_build/default/src/bin/ffsmc.bc -run test.fsm

dot: 
	../../_build/default/src/bin/ffsmc.bc -dot test.fsm

show: 
	../../_build/default/src/bin/ffsmc.bc -show test.fsm

vhdl: 
	../../_build/default/src/bin/ffsmc.bc -vhdl test.fsm

clean: 
	\rm -f *~
	\rm -f *.dot
	\rm -f *.vhdl

